const colors = {
  light: {
    text: "#1A2332",
    tint: "#1B4F8A",
    background: "#F0F4F8",
    foreground: "#1A2332",
    card: "#FFFFFF",
    cardForeground: "#1A2332",
    primary: "#1B4F8A",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EFF9",
    secondaryForeground: "#1B4F8A",
    muted: "#E8EFF9",
    mutedForeground: "#64748B",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#DDE6F0",
    input: "#FFFFFF",
  },
  dark: {
    text: "#E2EAF4",
    tint: "#5B8FCC",
    background: "#0D1421",
    foreground: "#E2EAF4",
    card: "#162032",
    cardForeground: "#E2EAF4",
    primary: "#5B8FCC",
    primaryForeground: "#FFFFFF",
    secondary: "#1E2E42",
    secondaryForeground: "#E2EAF4",
    muted: "#1E2E42",
    mutedForeground: "#94A3B8",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#243B58",
    input: "#162032",
  },
  radius: 12,
};

export default colors;
